### ISSUE TITLE
[crash]java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant below android O

### ISSUE THREAD

**Issue by Anonymitys** [googleads/googleads-ima-android#148] opened 2024-07-15 11:43 UTC
the method "com.google.ads.interactivemedia.v3.internal.zzok.zza()" uses "Instant" api which add in api level 26. this means when i use device below Android O, the crash happens

pls fixed it

**Comment by Kiro705** [comment] 2024-07-16 20:54
Hello @Anonymitys ,

Can you provide steps to reproduce this crash using the IMA sample apps?

Once I have that info, I can look into a fix for the samples.

Thank you,
Jackson
IMA SDK team

**Comment by Kiro705** [comment] 2024-07-17 23:04
Hello @Anonymitys ,

I think I was able to identify this issue, and it seems to be coming from the IMA SDK, and not an issue with the sample apps. I will continue to investigate, and let you know here when I have an update.

**Comment by Kiro705** [comment] 2024-07-18 20:29
Yes, we were able to confirm, this is an issue introduced in IMA Android SDK v3.34.0 specific to API level 25 and lower. 

The team is going to work on a new release to fix this, but would recommend using IMA v3.33.0 to support API level 25 and lower.

I'm going to close this GitHub issue, but the fix should be included in the next IMA SDK version.

**Closed** 2024-07-18 20:29 UTC
Labels: bug

**Comment by Anonymitys** [comment] 2024-08-27 07:55
> Yes, we were able to confirm, this is an issue introduced in IMA Android SDK v3.34.0 specific to API level 25 and lower.
> 
> The team is going to work on a new release to fix this, but would recommend using IMA v3.33.0 to support API level 25 and lower.
> 
> I'm going to close this GitHub issue, but the fix should be included in the next IMA SDK version.

OK，got it. by the way, Does IMA SDK 3.35.0 have detail release time?
