### ISSUE TITLE
Parser Error with empty timeOffset string

### ISSUE THREAD

**Issue by ayylmao21** [googleads/googleads-ima-android#24] opened 2017-09-11 19:46 UTC
Hi. Had an issue with the parser loading parts of ad requests from some URL.

The problem seems to be the XML Fragment contained at  https://pastebin.com/bqnbY4z5
It is the last child node of the root "vmap:VMAP" node, with multiple similar fragments preceding it. 
The response this fragment is a part of works inside of some HTML5/JS and flash based ad players.
I can't provide the tag URL I am using, or the full response. Sorry. I know this can hinder your ability to reproduce.

It breaks the Google Android IMA SDK the parser with
```I/Ads: Ad Error: Cannot parse the timeOffset value for the adslist response: .```
coming out in logcat.

Unfortunately, much of the code for the IMA SDK is obfuscated, so I can't trace and fix this issue locally. 
I was able to isolate it by serving my own versions of the VAST responses with the empty string replaced with 'start', but the server I'm requesting these from is not under my control, so I can't fix it myself either.

Also, I would make this issue on the repo for the IMA SDK itself, but there doesn't appear to be one.

**Comment by ypavlotsky** [comment] 2018-01-09 20:09
The issue is that your timeOffset property in <vmap:AdBreak> is set to the empty string '' and thus isn't valid VMAP. You need to provide a valid value, like 'start'.

**Comment by ypavlotsky** [comment] 2018-03-07 15:21
Closing this out.

**Closed by ypavlotsky** 2018-03-07 15:21 UTC
